export const erinnerungen = [
	{
		erinnerung: "Die IBAN fehlt noch. Neues Konto wird erst eingerichtet.",
		seite: "Stammdaten > Bankdaten",
		erstelltVon: "Melanie Schmid",
		faelligDatum: "2023-06-14",
		erledigt: false,
	},
	{
		erinnerung: "Notfallkontakt hat keine Telefonnummer",
		seite: "Stammdaten > Familienangehörige",
		erstelltVon: "Diren Akbulut",
		faelligDatum: "2023-06-01",
		erledigt: false,
	},
	{
		erinnerung: "",
		seite: "Stammdaten > Invalidität",
		erstelltVon: "Melanie Schmid",
		faelligDatum: "2023-06-14",
		erledigt: false,
	},
	{
		erinnerung: "Die IBAN fehlt noch. Neues Konto wird erst eingerichtet.",
		seite: "Stammdaten > Bankdaten",
		erstelltVon: "Melanie Schmid",
		faelligDatum: "2023-06-14",
		erledigt: false,
	},
	{
		erinnerung: "Notfallkontakt hat keine Telefonnummer",
		seite: "Stammdaten > Familienangehörige",
		erstelltVon: "Diren Akbulut",
		faelligDatum: "2023-06-01",
		erledigt: false,
	},
	{
		erinnerung: "",
		seite: "Stammdaten > Invalidität",
		erstelltVon: "Melanie Schmid",
		faelligDatum: "2023-06-14",
		erledigt: false,
	},
		{
		erinnerung: "Notfallkontakt hat keine Telefonnummer",
		seite: "Stammdaten > Familienangehörige",
		erstelltVon: "Diren Akbulut",
		faelligDatum: "2023-06-01",
		erledigt: false,
	},
	{
		erinnerung: "",
		seite: "Stammdaten > Invalidität",
		erstelltVon: "Melanie Schmid",
		faelligDatum: "2023-06-14",
		erledigt: false,
	},
]
