export const schulen = [
  {
    schule: 'Fachhochschule',
    adresse: '2750 Wr. Neustadt',
    fachrichtung: 'Projekt- und Prozessmanagement',
    abschluss: 'MSc.',
    von: '2019-09-03',
    bis: '2022-06-13',
  },
  {
    schule: 'HAK',
    adresse: '2750 Wr. Neustadt',
    fachrichtung: '',
    abschluss: 'Matura',
    von: '2014.09.03',
    bis: '2019.06.13',
  },
  {
    schule: 'Mittelschule',
    adresse: '2750 Wr. Neustadt',
    fachrichtung: '',
    abschluss: '',
    von: '2010.09.03',
    bis: '2014.06.13',
  }
  ];

export const schultypen = [
  "AHS",
  "AHS / Gymnasium",
  "Berufsbegleitende Ausbildung",
  "Centrum Ksztalcenia Zawodowego",
  "Colegiul Economic",
  "Ecole Superieure de Commerce",
  "Fachhochschule",
  "Fachhochschule Technikum Wien GmbH ",
  "FOS/BOS",
  "FS f. wirtschaftliche Berufe",
  "Gesamtschule",
  "Grundschule",
  "Gymnasium",
  "HAK/HAS",
  "Handelshoyskole",
  "Hauptschule",
  "HLA/HLW",
  "HLFS",
  "HLT/HLF",
  "Hochschule",
  "Hotelova akademia",
  "HTL",
  "Liceum",
  "Mittelschule",
  "Obchodna akademia",
  "Obchodni akademie",
  "Polytechn. Lehrgang",
  "Srednja sola",
  "Stredna odborna skola",
  "Stredna priemyselna skola",
  "Szakközepiskola",
  "Universidad",
  "Universidade",
  "Universita",
  "Universitat",
  "Universität",
  "Universität / Gornoslaska Wyzsza Szkola Handlowa",
  "Universitatea",
  "Universite",
  "Universitet",
  "Universitetas",
  "University",
  "Univerzita",
  "Univerzitet",
  "Uniwersytet",
  "Volksschule",
  "Wirtschaftsfachoberschule",
  "Wyzsza Szkola",
  "Zespol Szkol",
  ]

export const schuldaten = [
  { "Partnernummer": "100501","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Hans Kudlich-Gasse 30","Ort": "Gänserndorf","Postleitzahl": "2230" },
  { "Partnernummer": "100527","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Akademiestrasse 12","Ort": "Rohrbach in Oberösterreich","Postleitzahl": "4150" },
  { "Partnernummer": "101121","Schultyp": "Universität","Land": "AT","Adresse": "Universitätsstr. 65-67","Ort": "Klagenfurt","Postleitzahl": "9020" },
  { "Partnernummer": "1013865","Schultyp": "Universität / Gornoslaska Wyzsza Szkola Handlowa","Land": "PL","Adresse": "Ulica Harcerzy Wrzesnia 1939 r. 3","Ort": "Katowice","Postleitzahl": "40-659" },
  { "Partnernummer": "1042455","Schultyp": "Fachhochschule Technikum Wien GmbH ","Land": "AT","Adresse": "Höchstädtplatz 6 ","Ort": "Wien","Postleitzahl": "1200" },
  { "Partnernummer": "105330","Schultyp": "AHS","Land": "AT","Adresse": "Höchster Straße 32","Ort": "Dornbirn","Postleitzahl": "6850" },
  { "Partnernummer": "105331","Schultyp": "AHS","Land": "AT","Adresse": "Montfortplatz 16a","Ort": "Lauterach","Postleitzahl": "6923" },
  { "Partnernummer": "105333","Schultyp": "AHS","Land": "AT","Adresse": "Unterfeldstrasse 11","Ort": "Bludenz","Postleitzahl": "6700" },
  { "Partnernummer": "105334","Schultyp": "AHS","Land": "AT","Adresse": "Römerstrasse 14","Ort": "Landeck","Postleitzahl": "6500" },
  { "Partnernummer": "105552","Schultyp": "AHS","Land": "AT","Adresse": "MÃ¼hlefeldstraße 20","Ort": "Lustenau","Postleitzahl": "6890" },
  { "Partnernummer": "105607","Schultyp": "AHS","Land": "AT","Adresse": "Trentinerplatz 1","Ort": "Braunau am Inn","Postleitzahl": "5280" },
  { "Partnernummer": "105842","Schultyp": "AHS","Land": "AT","Adresse": "Schuhmeierplatz 7","Ort": "Wien","Postleitzahl": "1160" },
  { "Partnernummer": "106043","Schultyp": "HLFS","Land": "AT","Adresse": "Fernbach 37","Ort": "St.Florian","Postleitzahl": "4490" },
  { "Partnernummer": "106274","Schultyp": "University","Land": "GB","Adresse": "Claverton Down","Ort": "Bath","Postleitzahl": "BA2 7AY" },
  { "Partnernummer": "106857","Schultyp": "Universität","Land": "AT","Adresse": "Spitalgasse 23","Ort": "Wien","Postleitzahl": "1090" },
  { "Partnernummer": "107569","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Moserkellerweg","Ort": "Neumarkt am Wallersee","Postleitzahl": "5202" },
  { "Partnernummer": "107570","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Johann-Brunauer-Str. 2","Ort": "Salzburg","Postleitzahl": "5020" },
  { "Partnernummer": "107571","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Watzmannstrasse 40","Ort": "Oberndorf bei Salzburg","Postleitzahl": "5110" },
  { "Partnernummer": "107773","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Gartenstraße 1","Ort": "Wolfsberg","Postleitzahl": "9400" },
  { "Partnernummer": "107924","Schultyp": "Wirtschaftsfachoberschule","Land": "IT","Adresse": "Galileo-Galilei-Str. 33","Ort": "Meran","Postleitzahl": "39012" },
  { "Partnernummer": "107926","Schultyp": "AHS","Land": "AT","Adresse": "Geringergasse 2","Ort": "Wien","Postleitzahl": "1110" },
  { "Partnernummer": "107947","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Straßergasse 37-39","Ort": "Wien","Postleitzahl": "1190" },
  { "Partnernummer": "108944","Schultyp": "AHS","Land": "AT","Adresse": "Otto Glöckel-Weg 2","Ort": "Neunkirchen","Postleitzahl": "2620" },
  { "Partnernummer": "109297","Schultyp": "AHS","Land": "AT","Adresse": "Laaer-Berg-Strasse 25-29","Ort": "Wien","Postleitzahl": "1100" },
  { "Partnernummer": "111593","Schultyp": "AHS","Land": "AT","Adresse": "Gymnasiumstr.1","Ort": "Zwettl","Postleitzahl": "3910" },
  { "Partnernummer": "111669","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Maygasse 43","Ort": "Wien","Postleitzahl": "1130" },
  { "Partnernummer": "112324","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Maria Theresien-Straße 24","Ort": "Mödling","Postleitzahl": "2340" },
  { "Partnernummer": "112928","Schultyp": "Universite","Land": "FR","Adresse": "Ile du Saulcy","Ort": "Metz","Postleitzahl": "57045" },
  { "Partnernummer": "113101","Schultyp": "AHS","Land": "AT","Adresse": "Mösleweg 16","Ort": "Götzis","Postleitzahl": "6840" },
  { "Partnernummer": "11368","Schultyp": "AHS","Land": "AT","Adresse": "Linzer Straße 146","Ort": "Wien","Postleitzahl": "1140" },
  { "Partnernummer": "113893","Schultyp": "AHS","Land": "AT","Adresse": "Zemannstrasse 4","Ort": "Freistadt","Postleitzahl": "4240" },
  { "Partnernummer": "115136","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Donaulände 64","Ort": "Tulln","Postleitzahl": "3430" },
  { "Partnernummer": "116376","Schultyp": "Universität","Land": "AT","Adresse": "Oskar Kokoschka-Platz 2","Ort": "Wien","Postleitzahl": "1010" },
  { "Partnernummer": "116605","Schultyp": "Wirtschaftsfachoberschule","Land": "IT","Adresse": "Raetiastr. 295","Ort": "S.Ulrich in Gröden","Postleitzahl": "39046" },
  { "Partnernummer": "116765","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Flurweg 3","Ort": "Feldkirchen in Kärnten","Postleitzahl": "9560" },
  { "Partnernummer": "116767","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Franz-Xaver-Wirth Straße 3","Ort": "Villach","Postleitzahl": "9500" },
  { "Partnernummer": "117266","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Zernattostraße 2","Ort": "Spittal an der Drau","Postleitzahl": "9800" },
  { "Partnernummer": "118829","Schultyp": "HTL","Land": "AT","Adresse": "Davisstraße 5","Ort": "Hallein","Postleitzahl": "5400" },
  { "Partnernummer": "118870","Schultyp": "HTL","Land": "AT","Adresse": "Alaunstraße 29","Ort": "Krems","Postleitzahl": "3500" },
  { "Partnernummer": "119120","Schultyp": "AHS","Land": "AT","Adresse": "Moserhofstraße 7a","Ort": "Leoben","Postleitzahl": "8700" },
  { "Partnernummer": "121117","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Grössingerstraße 7","Ort": "Murau","Postleitzahl": "8850" },
  { "Partnernummer": "121223","Schultyp": "AHS","Land": "AT","Adresse": "Astgasse 3","Ort": "Wien","Postleitzahl": "1140" },
  { "Partnernummer": "122272","Schultyp": "HTL","Land": "AT","Adresse": "Raabser Straße 23","Ort": "Karlstein","Postleitzahl": "3822" },
  { "Partnernummer": "12260","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Schillerstr.10","Ort": "Neunkirchen","Postleitzahl": "2620" },
  { "Partnernummer": "124254","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Richard-Wagner-Straße 8","Ort": "Villach","Postleitzahl": "9500" },
  { "Partnernummer": "124278","Schultyp": "HTL","Land": "AT","Adresse": "Linker Iselweg 22","Ort": "Lienz","Postleitzahl": "9900" },
  { "Partnernummer": "125449","Schultyp": "Universidad","Land": "ES","Adresse": "C/Plaza de Santa Cruz 8","Ort": "Valladolid","Postleitzahl": "47002" },
  { "Partnernummer": "125718","Schultyp": "AHS","Land": "AT","Adresse": "Carnerigasse 30","Ort": "Graz","Postleitzahl": "8010" },
  { "Partnernummer": "126120","Schultyp": "AHS","Land": "AT","Adresse": "Maderspergerstraße 3","Ort": "Kufstein","Postleitzahl": "6330" },
  { "Partnernummer": "126744","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Karl-Vogl-Str. 21","Ort": "Zell am See","Postleitzahl": "5700" },
  { "Partnernummer": "127432","Schultyp": "Universidad","Land": "ES","Adresse": "C/ Madrid, 126","Ort": "Getafe","Postleitzahl": "28903" },
  { "Partnernummer": "128824","Schultyp": "HTL","Land": "AT","Adresse": "Viktor-Kaplan-Straße 1","Ort": "Kapfenberg","Postleitzahl": "8605" },
  { "Partnernummer": "128838","Schultyp": "HTL","Land": "AT","Adresse": "Ibererstraße 15-21","Ort": "Graz","Postleitzahl": "8051" },
  { "Partnernummer": "128841","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Weidengasse 1","Ort": "Lienz","Postleitzahl": "9900" },
  { "Partnernummer": "129543","Schultyp": "AHS","Land": "AT","Adresse": "Weissenbachgasse 33","Ort": "Telfs","Postleitzahl": "6410" },
  { "Partnernummer": "129692","Schultyp": "Fachhochschule","Land": "AT","Adresse": "Alte Poststraße 149","Ort": "Graz","Postleitzahl": "8020" },
  { "Partnernummer": "133082","Schultyp": "AHS","Land": "AT","Adresse": "Fichtnergasse 15","Ort": "Wien","Postleitzahl": "1130" },
  { "Partnernummer": "137821","Schultyp": "AHS","Land": "AT","Adresse": "Sandgasse 40","Ort": "Graz","Postleitzahl": "8010" },
  { "Partnernummer": "138403","Schultyp": "AHS","Land": "AT","Adresse": "Dirnbergerstraße 43","Ort": "Perg","Postleitzahl": "4320" },
  { "Partnernummer": "138405","Schultyp": "AHS","Land": "AT","Adresse": "Beethovenstraße 6","Ort": "Ried im Innkreis","Postleitzahl": "4910" },
  { "Partnernummer": "138407","Schultyp": "AHS","Land": "AT","Adresse": "Stift-Viktring-Str. 25","Ort": "Viktring","Postleitzahl": "9073" },
  { "Partnernummer": "138410","Schultyp": "AHS","Land": "AT","Adresse": "Schillerstraße 13","Ort": "Feldkirch","Postleitzahl": "6800" },
  { "Partnernummer": "138873","Schultyp": "Wirtschaftsfachoberschule","Land": "IT","Adresse": "Maria-Montessori-Straße 4","Ort": "Brixen","Postleitzahl": "39042" },
  { "Partnernummer": "139435","Schultyp": "AHS","Land": "AT","Adresse": "Kandlgasse 39","Ort": "Wien","Postleitzahl": "1070" },
  { "Partnernummer": "139497","Schultyp": "AHS","Land": "AT","Adresse": "Geblergasse 56-58","Ort": "Wien","Postleitzahl": "1170" },
  { "Partnernummer": "13973","Schultyp": "AHS","Land": "AT","Adresse": "Franklinstrasse 21","Ort": "Wien","Postleitzahl": "1210" },
  { "Partnernummer": "139731","Schultyp": "AHS","Land": "AT","Adresse": "Stubenbastei 6-8","Ort": "Wien","Postleitzahl": "1010" },
  { "Partnernummer": "141351","Schultyp": "Universite","Land": "FR","Adresse": "4 rue Blaise Pascal, CS90032","Ort": "Strasbourg","Postleitzahl": "67081" },
  { "Partnernummer": "141352","Schultyp": "Universite","Land": "FR","Adresse": "72 Route du Rhin","Ort": "Illkirch Graffenstaden","Postleitzahl": "67411" },
  { "Partnernummer": "143704","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Kreuzgasse 9a","Ort": "Landeck","Postleitzahl": "6500" },
  { "Partnernummer": "143705","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Klostergasse 18","Ort": "Leibnitz","Postleitzahl": "8430" },
  { "Partnernummer": "143706","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Klosterplatz 1","Ort": "Lambach","Postleitzahl": "4650" },
  { "Partnernummer": "143707","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Mosteckyplatz 1","Ort": "Klagenfurt","Postleitzahl": "9020" },
  { "Partnernummer": "143708","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Kumpfgasse 21/1","Ort": "Klagenfurt","Postleitzahl": "9020" },
  { "Partnernummer": "143709","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Neualmerstrasse 28","Ort": "Hallein","Postleitzahl": "5400" },
  { "Partnernummer": "143710","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Liechtensteinerstr. 50","Ort": "Feldkirch","Postleitzahl": "6800" },
  { "Partnernummer": "143711","Schultyp": "HAK/HAS","Land": "AT","Adresse": "BrÃ¼ckengasse 2","Ort": "Bruck an der Mur","Postleitzahl": "8600" },
  { "Partnernummer": "143712","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Hinterfeldgasse 19","Ort": "Bregenz","Postleitzahl": "6900" },
  { "Partnernummer": "143714","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Raitfeldstrasse 3","Ort": "Braunau am Inn","Postleitzahl": "5280" },
  { "Partnernummer": "143715","Schultyp": "Wirtschaftsfachoberschule","Land": "IT","Adresse": "Rennweg 3","Ort": "Meran","Postleitzahl": "39012" },
  { "Partnernummer": "143723","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Almer Strasse 33","Ort": "Saalfelden","Postleitzahl": "5760" },
  { "Partnernummer": "143725","Schultyp": "HLFS","Land": "AT","Adresse": "Raumberg 38","Ort": "Irdning","Postleitzahl": "8952" },
  { "Partnernummer": "143726","Schultyp": "HLFS","Land": "AT","Adresse": "Ursprungstrasse 4","Ort": "Elixhausen","Postleitzahl": "5161" },
  { "Partnernummer": "143727","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Innsbrucker Strasse 34","Ort": "Wörgl","Postleitzahl": "6300" },
  { "Partnernummer": "143728","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Lasaberweg 10","Ort": "Tamsweg","Postleitzahl": "5580" },
  { "Partnernummer": "143730","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Alte Bundesstrasse 11","Ort": "St.Johann im Pongau","Postleitzahl": "5600" },
  { "Partnernummer": "143732","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Schulstrasse 445","Ort": "Schärding","Postleitzahl": "4780" },
  { "Partnernummer": "143733","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Johann-Brunauer-Str. 4","Ort": "Salzburg","Postleitzahl": "5020" },
  { "Partnernummer": "143734","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Gartenstrasse 1","Ort": "Ried im Innkreis","Postleitzahl": "4910" },
  { "Partnernummer": "143735","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Gymnasiumstrasse 8","Ort": "Reutte","Postleitzahl": "6600" },
  { "Partnernummer": "143737","Schultyp": "Wirtschaftsfachoberschule","Land": "IT","Adresse": "Guntschnastr. 1","Ort": "Bozen","Postleitzahl": "39100" },
  { "Partnernummer": "143738","Schultyp": "Wirtschaftsfachoberschule","Land": "IT","Adresse": "Freisingerstraße 13/A","Ort": "Innichen","Postleitzahl": "39038" },
  { "Partnernummer": "143739","Schultyp": "Wirtschaftsfachoberschule","Land": "IT","Adresse": "Roenstraße 12","Ort": "Bozen","Postleitzahl": "39100" },
  { "Partnernummer": "143740","Schultyp": "Wirtschaftsfachoberschule","Land": "IT","Adresse": "Staatsstr. 9","Ort": "Mals im Vinschgau","Postleitzahl": "39024" },
  { "Partnernummer": "143741","Schultyp": "Wirtschaftsfachoberschule","Land": "IT","Adresse": "Pfarre 1","Ort": "Sand in Taufers","Postleitzahl": "39032" },
  { "Partnernummer": "143742","Schultyp": "Wirtschaftsfachoberschule","Land": "IT","Adresse": "Plawennpark 3","Ort": "Schlanders","Postleitzahl": "39028" },
  { "Partnernummer": "143743","Schultyp": "Wirtschaftsfachoberschule","Land": "IT","Adresse": "St. Margarethenstr. 10","Ort": "Sterzing","Postleitzahl": "39049" },
  { "Partnernummer": "143744","Schultyp": "Wirtschaftsfachoberschule","Land": "IT","Adresse": "Josef-Ferrari-Strasse 12","Ort": "Bruneck","Postleitzahl": "39031" },
  { "Partnernummer": "144480","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Hetzendorferstr. 66-68","Ort": "Wien","Postleitzahl": "1120" },
  { "Partnernummer": "146021","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Badgasse 5","Ort": "Oberwart","Postleitzahl": "7400" },
  { "Partnernummer": "146026","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Polgarstr. 24","Ort": "Wien","Postleitzahl": "1220" },
  { "Partnernummer": "147761","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Brauhausstr.10","Ort": "Freistadt","Postleitzahl": "4240" },
  { "Partnernummer": "147762","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Dirnberger Straße 41","Ort": "Perg","Postleitzahl": "4320" },
  { "Partnernummer": "148611","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Alte Bundesstraße 12","Ort": "St.Johann im Pongau","Postleitzahl": "5600" },
  { "Partnernummer": "148914","Schultyp": "Fachhochschule","Land": "AT","Adresse": "Wehrgrabengasse 1-3","Ort": "Steyr","Postleitzahl": "4400" },
  { "Partnernummer": "149716","Schultyp": "Universität","Land": "AT","Adresse": "Universitätsstraße 3","Ort": "Graz","Postleitzahl": "8010" },
  { "Partnernummer": "149869","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Schulstraße 7","Ort": "Pinkafeld","Postleitzahl": "7423" },
  { "Partnernummer": "150696","Schultyp": "University","Land": "GB","Adresse": "","Ort": "Stirling","Postleitzahl": "FK9 4LA" },
  { "Partnernummer": "151514","Schultyp": "AHS","Land": "AT","Adresse": "Beethovenplatz 1","Ort": "Wien","Postleitzahl": "1010" },
  { "Partnernummer": "152820","Schultyp": "AHS","Land": "AT","Adresse": "Dr. Schauer-Straße 9","Ort": "Wels","Postleitzahl": "4600" },
  { "Partnernummer": "152984","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Waldstraße 1","Ort": "St.Pölten","Postleitzahl": "3100" },
  { "Partnernummer": "153393","Schultyp": "HTL","Land": "AT","Adresse": "Bahnhofstraße 42","Ort": "Vöcklabruck","Postleitzahl": "4840" },
  { "Partnernummer": "154238","Schultyp": "Universität","Land": "AT","Adresse": "Dr.Karl-Dorrek-Straße 30","Ort": "Krems","Postleitzahl": "3500" },
  { "Partnernummer": "154593","Schultyp": "AHS","Land": "AT","Adresse": "Spittelwiese 14","Ort": "Linz","Postleitzahl": "4020" },
  { "Partnernummer": "158391","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Stelzhamerstraße 20","Ort": "Wels","Postleitzahl": "4600" },
  { "Partnernummer": "158867","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Brennerweg 8","Ort": "Mistelbach","Postleitzahl": "2130" },
  { "Partnernummer": "158869","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Anton Bruckner-Straße 39","Ort": "Laa an der Thaya","Postleitzahl": "2136" },
  { "Partnernummer": "160290","Schultyp": "Ecole Superieure de Commerce","Land": "FR","Adresse": "102, Rue de Coureilles","Ort": "La Rochelle","Postleitzahl": "17024" },
  { "Partnernummer": "161225","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Pfarrgasse 6","Ort": "Feldbach","Postleitzahl": "8330" },
  { "Partnernummer": "161247","Schultyp": "Fachhochschule","Land": "AT","Adresse": "Johannes Gutenberg-Straße 3","Ort": "Wiener Neustadt","Postleitzahl": "2700" },
  { "Partnernummer": "161425","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Englweg 2","Ort": "Vöcklabruck","Postleitzahl": "4840" },
  { "Partnernummer": "161426","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Friesacherstraße 4","Ort": "Althofen","Postleitzahl": "9330" },
  { "Partnernummer": "161965","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Lagergasse 11","Ort": "Deutschlandsberg","Postleitzahl": "8530" },
  { "Partnernummer": "164416","Schultyp": "Universität","Land": "AT","Adresse": "Universitätsring 1","Ort": "Wien","Postleitzahl": "1010" },
  { "Partnernummer": "166306","Schultyp": "Universität","Land": "AT","Adresse": "Innrain 52","Ort": "Innsbruck","Postleitzahl": "6020" },
  { "Partnernummer": "166439","Schultyp": "Hochschule","Land": "DE","Adresse": "Hochschulstrasse 1","Ort": "Rosenheim","Postleitzahl": "83024" },
  { "Partnernummer": "166645","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Pocksteinerstraße 3","Ort": "Waidhofen an der Ybbs","Postleitzahl": "3340" },
  { "Partnernummer": "168187","Schultyp": "Universite","Land": "FR","Adresse": "34 rue du Grillenbreit, BP 50568","Ort": "Colmar","Postleitzahl": "68008" },
  { "Partnernummer": "168597","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Pernerstorfergasse 77","Ort": "Wien","Postleitzahl": "1100" },
  { "Partnernummer": "170106","Schultyp": "AHS","Land": "AT","Adresse": "Billrothstraße 73","Ort": "Wien","Postleitzahl": "1190" },
  { "Partnernummer": "170623","Schultyp": "University","Land": "GB","Adresse": "College Gate","Ort": "St Andrews","Postleitzahl": "KY16 9AJ" },
  { "Partnernummer": "170625","Schultyp": "University","Land": "GB","Adresse": "2 Charles Street","Ort": "Edinburgh","Postleitzahl": "EH8 9AD" },
  { "Partnernummer": "170626","Schultyp": "University","Land": "GB","Adresse": "King's College","Ort": "Aberdeen","Postleitzahl": "AB24 3FX" },
  { "Partnernummer": "170675","Schultyp": "University","Land": "GB","Adresse": "Garthdee House, Garthdee Road","Ort": "Aberdeen","Postleitzahl": "AB10 7QB" },
  { "Partnernummer": "172866","Schultyp": "AHS","Land": "AT","Adresse": "Petersgasse 1","Ort": "Graz","Postleitzahl": "8010" },
  { "Partnernummer": "173603","Schultyp": "AHS","Land": "AT","Adresse": "Friesacher Straße 4","Ort": "Treibach-Althofen","Postleitzahl": "9330" },
  { "Partnernummer": "175403","Schultyp": "Gymnasium","Land": "DE","Adresse": "Kapuzinerstraße 29","Ort": "Bamberg","Postleitzahl": "96047" },
  { "Partnernummer": "175412","Schultyp": "Gymnasium","Land": "DE","Adresse": "Sebastianstrasse 28","Ort": "Weiden","Postleitzahl": "92637" },
  { "Partnernummer": "175413","Schultyp": "Gymnasium","Land": "DE","Adresse": "Pestalozzistrasse 10","Ort": "Neustadt","Postleitzahl": "96465" },
  { "Partnernummer": "175414","Schultyp": "Gymnasium","Land": "DE","Adresse": "Freudenhain 2","Ort": "Passau","Postleitzahl": "94034" },
  { "Partnernummer": "178393","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Margaretenstraße 65","Ort": "Wien","Postleitzahl": "1050" },
  { "Partnernummer": "178883","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Habertstraße 5","Ort": "Gmunden","Postleitzahl": "4810" },
  { "Partnernummer": "183500","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Langenloiser-Straße 22","Ort": "Krems","Postleitzahl": "3500" },
  { "Partnernummer": "184313","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Weidengasse 1","Ort": "Lienz","Postleitzahl": "9900" },
  { "Partnernummer": "186284","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Michael Koch-Straße 44","Ort": "Mattersburg","Postleitzahl": "7210" },
  { "Partnernummer": "186479","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Realschulstraße 6","Ort": "FÃ¼rstenfeld","Postleitzahl": "8280" },
  { "Partnernummer": "186921","Schultyp": "AHS","Land": "AT","Adresse": "Klostergasse 25","Ort": "Wien","Postleitzahl": "1180" },
  { "Partnernummer": "188839","Schultyp": "HTL","Land": "AT","Adresse": "Donaustadtstraße 45","Ort": "Wien","Postleitzahl": "1220" },
  { "Partnernummer": "191294","Schultyp": "HTL","Land": "AT","Adresse": "Fischergasse 30","Ort": "Wels","Postleitzahl": "4600" },
  { "Partnernummer": "192733","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Schulgasse 4","Ort": "Oberwart","Postleitzahl": "7400" },
  { "Partnernummer": "192779","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Untere Augartenstrasse 9","Ort": "Wien","Postleitzahl": "1020" },
  { "Partnernummer": "192781","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Gymnasiumstraße 19","Ort": "Oberpullendorf","Postleitzahl": "7350" },
  { "Partnernummer": "193241","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Stadionstr. 8-10","Ort": "Judenburg","Postleitzahl": "8750" },
  { "Partnernummer": "194790","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Dr.-Karl-Renner-Ring 40","Ort": "Liezen","Postleitzahl": "8940" },
  { "Partnernummer": "196028","Schultyp": "AHS","Land": "AT","Adresse": "Grazer Straße 27","Ort": "Bad Ischl","Postleitzahl": "4820" },
  { "Partnernummer": "197468","Schultyp": "AHS","Land": "AT","Adresse": "Boerhaavegasse 15","Ort": "Wien","Postleitzahl": "1030" },
  { "Partnernummer": "197584","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Bad Kissingen-Platz 3","Ort": "Eisenstadt","Postleitzahl": "7001" },
  { "Partnernummer": "197588","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Akademiestr.12","Ort": "Wien","Postleitzahl": "1010" },
  { "Partnernummer": "197649","Schultyp": "HTL","Land": "AT","Adresse": "Technikerstr. 1-5","Ort": "Mödling","Postleitzahl": "2340" },
  { "Partnernummer": "197913","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Stefan-Fadinger-Straße 36","Ort": "Amstetten","Postleitzahl": "3300" },
  { "Partnernummer": "197914","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Kaltenbachstrasse 19","Ort": "Bad Ischl","Postleitzahl": "4820" },
  { "Partnernummer": "197918","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Bräuhausstraße 3","Ort": "Eferding","Postleitzahl": "4070" },
  { "Partnernummer": "197922","Schultyp": "Fachhochschule","Land": "AT","Adresse": "Campus 1","Ort": "Eisenstadt","Postleitzahl": "7000" },
  { "Partnernummer": "197925","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Franklinstraße 24","Ort": "Wien","Postleitzahl": "1210" },
  { "Partnernummer": "197926","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Kirchenplatz 1","Ort": "Frauenkirchen","Postleitzahl": "7132" },
  { "Partnernummer": "197928","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Geringergasse 2","Ort": "Wien","Postleitzahl": "1110" },
  { "Partnernummer": "197929","Schultyp": "AHS","Land": "AT","Adresse": "Gymnasiumstraße 5","Ort": "GmÃ¼nd","Postleitzahl": "3950" },
  { "Partnernummer": "197931","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Otto Glöckel-Straße 6","Ort": "GmÃ¼nd","Postleitzahl": "3950" },
  { "Partnernummer": "197933","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Hamerlingplatz 5-6","Ort": "Wien","Postleitzahl": "1080" },
  { "Partnernummer": "197937","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Edelseegasse 13","Ort": "Hartberg","Postleitzahl": "8230" },
  { "Partnernummer": "197940","Schultyp": "AHS","Land": "AT","Adresse": "Puchheimgasse 21","Ort": "Horn","Postleitzahl": "3580" },
  { "Partnernummer": "198058","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Gartengasse 1","Ort": "Horn","Postleitzahl": "3580" },
  { "Partnernummer": "198072","Schultyp": "Fachhochschule","Land": "AT","Adresse": "Piaristengasse 1","Ort": "Krems","Postleitzahl": "3500" },
  { "Partnernummer": "198079","Schultyp": "HLT/HLF","Land": "AT","Adresse": "Bundesschulstraße 4","Ort": "Neusiedl am See","Postleitzahl": "7100" },
  { "Partnernummer": "198084","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Schönborngasse 3-5","Ort": "Wien","Postleitzahl": "1080" },
  { "Partnernummer": "198088","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Kirchengasse 44","Ort": "Stegersbach","Postleitzahl": "7551" },
  { "Partnernummer": "198089","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Schulstraße 59","Ort": "Traun","Postleitzahl": "4050" },
  { "Partnernummer": "198092","Schultyp": "AHS","Land": "AT","Adresse": "Gymnasiumstraße 1","Ort": "Waidhofen an der Thaya","Postleitzahl": "3830" },
  { "Partnernummer": "198096","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Vitiser Straße 17","Ort": "Waidhofen an der Thaya","Postleitzahl": "3830" },
  { "Partnernummer": "198097","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Stelzhamerstraße 20","Ort": "Wels","Postleitzahl": "4600" },
  { "Partnernummer": "198099","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Ungargasse 29","Ort": "Wiener Neustadt","Postleitzahl": "2700" },
  { "Partnernummer": "198103","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Schulring 1","Ort": "Ybbs an der Donau","Postleitzahl": "3370" },
  { "Partnernummer": "198104","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Hammerweg 1","Ort": "Zwettl","Postleitzahl": "3910" },
  { "Partnernummer": "198106","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Klosterstraße 10","Ort": "Zwettl","Postleitzahl": "3910" },
  { "Partnernummer": "199542","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Fasangasse 4","Ort": "Wien","Postleitzahl": "1030" },
  { "Partnernummer": "20027","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Fischamender Str.21-23","Ort": "Bruck an der Leitha","Postleitzahl": "2460" },
  { "Partnernummer": "200724","Schultyp": "AHS","Land": "AT","Adresse": "Prof. Janezic-Platz 1","Ort": "Klagenfurt","Postleitzahl": "9020" },
  { "Partnernummer": "200847","Schultyp": "AHS","Land": "AT","Adresse": "Akademiestraße 19","Ort": "Salzburg","Postleitzahl": "5020" },
  { "Partnernummer": "200889","Schultyp": "Fachhochschule","Land": "AT","Adresse": "Hochschulstraße 1","Ort": "Dornbirn","Postleitzahl": "6850" },
  { "Partnernummer": "201038","Schultyp": "Fachhochschule","Land": "AT","Adresse": "Andreas-Hofer-Str. 7","Ort": "Kufstein","Postleitzahl": "6330" },
  { "Partnernummer": "201039","Schultyp": "HLFS","Land": "AT","Adresse": "Glantalstr.59/Schloss Pitzelstätten","Ort": "Wölfnitz","Postleitzahl": "9061" },
  { "Partnernummer": "201040","Schultyp": "HLT/HLF","Land": "AT","Adresse": "Klostergasse 5","Ort": "Innsbruck","Postleitzahl": "6020" },
  { "Partnernummer": "201043","Schultyp": "HLT/HLF","Land": "AT","Adresse": "Neubauweg 9","Ort": "St.Johann in Tirol","Postleitzahl": "6380" },
  { "Partnernummer": "202604","Schultyp": "AHS","Land": "AT","Adresse": "Peraustraße 10","Ort": "Villach","Postleitzahl": "9500" },
  { "Partnernummer": "202794","Schultyp": "AHS","Land": "AT","Adresse": "Petrinumstraße 12","Ort": "Linz","Postleitzahl": "4040" },
  { "Partnernummer": "207489","Schultyp": "HLFS","Land": "AT","Adresse": "Birkenweg 8","Ort": "Kematen in Tirol","Postleitzahl": "6175" },
  { "Partnernummer": "212312","Schultyp": "HLT/HLF","Land": "AT","Adresse": "Schwimmbadweg","Ort": "Zell am Ziller","Postleitzahl": "6280" },
  { "Partnernummer": "212386","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Wallerer Straße 32","Ort": "Wels","Postleitzahl": "4600" },
  { "Partnernummer": "212392","Schultyp": "AHS","Land": "AT","Adresse": "Anton-Bruckner-Str. 16","Ort": "Wels","Postleitzahl": "4600" },
  { "Partnernummer": "214529","Schultyp": "HTL","Land": "AT","Adresse": "Molkereistraße 4","Ort": "Ried im Innkreis","Postleitzahl": "4910" },
  { "Partnernummer": "220060","Schultyp": "AHS","Land": "AT","Adresse": "Innsbruckerstraße 34","Ort": "Wörgl","Postleitzahl": "6300" },
  { "Partnernummer": "220061","Schultyp": "AHS","Land": "AT","Adresse": "Lichtenbergstraße 13","Ort": "Saalfelden","Postleitzahl": "5760" },
  { "Partnernummer": "221160","Schultyp": "AHS","Land": "AT","Adresse": "Birkengasse 1","Ort": "Birkfeld","Postleitzahl": "8190" },
  { "Partnernummer": "221642","Schultyp": "AHS","Land": "AT","Adresse": "Schloß-Straße 31a","Ort": "Vöcklabruck","Postleitzahl": "4840" },
  { "Partnernummer": "222203","Schultyp": "Universität","Land": "DE","Adresse": "Innstraße 41","Ort": "Passau","Postleitzahl": "94032" },
  { "Partnernummer": "222468","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Aubrunnerweg 4","Ort": "Linz","Postleitzahl": "4040" },
  { "Partnernummer": "222811","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Ungargasse 69","Ort": "Wien","Postleitzahl": "1030" },
  { "Partnernummer": "224344","Schultyp": "Fachhochschule","Land": "AT","Adresse": "Primoschgasse 8","Ort": "Klagenfurt","Postleitzahl": "9020" },
  { "Partnernummer": "224423","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Michaelistraße 70","Ort": "Braunau am Inn","Postleitzahl": "5280" },
  { "Partnernummer": "225248","Schultyp": "Gymnasium","Land": "DE","Adresse": "Königstraße 25","Ort": "Rosenheim","Postleitzahl": "83022" },
  { "Partnernummer": "226772","Schultyp": "Universita","Land": "IT","Adresse": "Piazza Universita 1","Ort": "Bozen","Postleitzahl": "39100" },
  { "Partnernummer": "226773","Schultyp": "Universita","Land": "IT","Adresse": "Via Calepina 14","Ort": "Trento","Postleitzahl": "38122" },
  { "Partnernummer": "226968","Schultyp": "Universität","Land": "AT","Adresse": "Altenbergerstraße 69","Ort": "Linz","Postleitzahl": "4040" },
  { "Partnernummer": "227552","Schultyp": "HLT/HLF","Land": "AT","Adresse": "Seeweg 2","Ort": "Retz","Postleitzahl": "2070" },
  { "Partnernummer": "228467","Schultyp": "Gymnasium","Land": "DE","Adresse": "Kapellenweg 43 (Postfach 1226)","Ort": "Raubling","Postleitzahl": "83064" },
  { "Partnernummer": "231194","Schultyp": "Universität","Land": "DE","Adresse": "Bibliothekstraße 1","Ort": "Bremen","Postleitzahl": "28359" },
  { "Partnernummer": "232764","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Weinhartstraße 4","Ort": "Innsbruck","Postleitzahl": "6020" },
  { "Partnernummer": "233775","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Technikerstraße 7a","Ort": "Innsbruck","Postleitzahl": "6020" },
  { "Partnernummer": "235478","Schultyp": "Universite","Land": "FR","Adresse": "1, rue Alfred Werner","Ort": "Mulhouse Cedex","Postleitzahl": "68093" },
  { "Partnernummer": "235479","Schultyp": "Ecole Superieure de Commerce","Land": "FR","Adresse": "29 rue Sambin, BP 50608","Ort": "Dijon Cedex","Postleitzahl": "21006" },
  { "Partnernummer": "235480","Schultyp": "Ecole Superieure de Commerce","Land": "FR","Adresse": "12 rue Pierre SÃ©mard, BP 127","Ort": "Grenoble","Postleitzahl": "38000" },
  { "Partnernummer": "235482","Schultyp": "Hochschule","Land": "DE","Adresse": "Jakob-Kienzle-Str. 17","Ort": "Villingen-Schwenningen","Postleitzahl": "78054" },
  { "Partnernummer": "235483","Schultyp": "Ecole Superieure de Commerce","Land": "FR","Adresse": "22, boulevard du Fort de Vaux","Ort": "Paris","Postleitzahl": "75017" },
  { "Partnernummer": "235484","Schultyp": "Universite","Land": "FR","Adresse": "Esplanade Erasme, BP 27877","Ort": "Dijon","Postleitzahl": "21000" },
  { "Partnernummer": "240670","Schultyp": "Universität","Land": "AT","Adresse": "Schillerplatz 3","Ort": "Wien","Postleitzahl": "1010" },
  { "Partnernummer": "243112","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Dr.-Arthur-Lemisch-Straße 15","Ort": "St.Veit an der Glan","Postleitzahl": "9300" },
  { "Partnernummer": "249341","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Germergasse 5","Ort": "Baden","Postleitzahl": "2500" },
  { "Partnernummer": "251208","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Burgplatz 1","Ort": "Wiener Neustadt","Postleitzahl": "2700" },
  { "Partnernummer": "252410","Schultyp": "AHS","Land": "AT","Adresse": "Zernattostraße 10","Ort": "Spittal an der Drau","Postleitzahl": "9800" },
  { "Partnernummer": "252546","Schultyp": "HTL","Land": "AT","Adresse": "Markt 136","Ort": "Kuchl","Postleitzahl": "5431" },
  { "Partnernummer": "255038","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Rudigierstraße 6","Ort": "Linz","Postleitzahl": "4020" },
  { "Partnernummer": "25636","Schultyp": "HLT/HLF","Land": "AT","Adresse": "Kathrinstraße 2","Ort": "Bad Ischl","Postleitzahl": "4820" },
  { "Partnernummer": "259270","Schultyp": "HLT/HLF","Land": "AT","Adresse": "Langenloiser Straße 22","Ort": "Krems","Postleitzahl": "3500" },
  { "Partnernummer": "261391","Schultyp": "AHS","Land": "AT","Adresse": "Karl-Vogt-Strasse 21","Ort": "Zell am See","Postleitzahl": "5700" },
  { "Partnernummer": "261509","Schultyp": "Universität","Land": "AT","Adresse": "Hauptplatz 8","Ort": "Linz","Postleitzahl": "4010" },
  { "Partnernummer": "264841","Schultyp": "AHS","Land": "AT","Adresse": "Hptm.-Kluibenschedl-Str 2","Ort": "Stams","Postleitzahl": "6422" },
  { "Partnernummer": "270846","Schultyp": "AHS","Land": "AT","Adresse": "Blumenstrasse 4","Ort": "Bregenz","Postleitzahl": "6900" },
  { "Partnernummer": "275939","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Gartengasse 1","Ort": "Horn","Postleitzahl": "3580" },
  { "Partnernummer": "281657","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Roseggergasse 10","Ort": "MÃ¼rzzuschlag","Postleitzahl": "8680" },
  { "Partnernummer": "282491","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Bankmannring 1","Ort": "Korneuburg","Postleitzahl": "2100" },
  { "Partnernummer": "286541","Schultyp": "Universität","Land": "AT","Adresse": "Leonhardstraße 15","Ort": "Graz","Postleitzahl": "8010" },
  { "Partnernummer": "287910","Schultyp": "HTL","Land": "AT","Adresse": "Im Vogelsang 8","Ort": "Waidhofen an der Ybbs","Postleitzahl": "3340" },
  { "Partnernummer": "287946","Schultyp": "Fachhochschule","Land": "AT","Adresse": "Werk-VI-Straße 46","Ort": "Kapfenberg","Postleitzahl": "8605" },
  { "Partnernummer": "291740","Schultyp": "Universita","Land": "IT","Adresse": "Piazza dell'Ateneo Nuovo 1","Ort": "Milano","Postleitzahl": "20126" },
  { "Partnernummer": "292013","Schultyp": "HLT/HLF","Land": "AT","Adresse": "Bergheidengasse 5-19","Ort": "Wien","Postleitzahl": "1130" },
  { "Partnernummer": "293680","Schultyp": "HLT/HLF","Land": "AT","Adresse": "Kleßheimer Straße 22","Ort": "Siezenheim","Postleitzahl": "5071" },
  { "Partnernummer": "293827","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Erdbergstraße 70","Ort": "Wien","Postleitzahl": "1030" },
  { "Partnernummer": "299580","Schultyp": "Universita","Land": "IT","Adresse": "Via Giovanni Paolo II,132","Ort": "Fisciano","Postleitzahl": "84084" },
  { "Partnernummer": "30227","Schultyp": "HTL","Land": "AT","Adresse": "Limesstraße 12-14","Ort": "Leonding","Postleitzahl": "4060" },
  { "Partnernummer": "302990","Schultyp": "Universidade","Land": "PT","Adresse": "Rua Dr. Roberto Frias","Ort": "Porto","Postleitzahl": "4000" },
  { "Partnernummer": "304622","Schultyp": "AHS","Land": "AT","Adresse": "Hochstraße 1","Ort": "Mattersburg","Postleitzahl": "7210" },
  { "Partnernummer": "304831","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Perlasgasse 10","Ort": "Biedermannsdorf","Postleitzahl": "2362" },
  { "Partnernummer": "305177","Schultyp": "HTL","Land": "AT","Adresse": "Spengergasse 20","Ort": "Wien","Postleitzahl": "1050" },
  { "Partnernummer": "306976","Schultyp": "Fachhochschule","Land": "AT","Adresse": "Matthias Corvinus-Straße 15","Ort": "St.Pölten","Postleitzahl": "3100" },
  { "Partnernummer": "310147","Schultyp": "University","Land": "BG","Adresse": "Boulevard Kliment Ohridski 8","Ort": "Sofia","Postleitzahl": "1000" },
  { "Partnernummer": "319549","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Professor-Janezic-Platz 1","Ort": "Klagenfurt","Postleitzahl": "9020" },
  { "Partnernummer": "32054","Schultyp": "Universität","Land": "AT","Adresse": "Welthandelsplatz 1","Ort": "Wien","Postleitzahl": "1020" },
  { "Partnernummer": "325529","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Brennerweg 8","Ort": "Mistelbach","Postleitzahl": "2130" },
  { "Partnernummer": "327185","Schultyp": "HLFS","Land": "AT","Adresse": "Wiener Straße 74","Ort": "Klosterneuburg","Postleitzahl": "3400" },
  { "Partnernummer": "327604","Schultyp": "University","Land": "GB","Adresse": "Woodhouse Lane","Ort": "Leeds","Postleitzahl": "LS2 9JT" },
  { "Partnernummer": "335526","Schultyp": "AHS","Land": "AT","Adresse": "Gärntergasse 5-7","Ort": "Gänserndorf","Postleitzahl": "2230" },
  { "Partnernummer": "336738","Schultyp": "HLA/HLW","Land": "AT","Adresse": "MÃ¼hlgasse 35","Ort": "Hollabrunn","Postleitzahl": "2020" },
  { "Partnernummer": "338419","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Frohsdorfer Hauptstraße 28","Ort": "Lanzenkirchen","Postleitzahl": "2821" },
  { "Partnernummer": "340105","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Dr.-Karl-Widdmannstr. 40","Ort": "Weiz","Postleitzahl": "8160" },
  { "Partnernummer": "342968","Schultyp": "Universität","Land": "DE","Adresse": "Große Scharnstraße 59","Ort": "Frankfurt/Oder","Postleitzahl": "15230" },
  { "Partnernummer": "346607","Schultyp": "University","Land": "GB","Adresse": "Talbot Campus, Christchurch House","Ort": "Poole","Postleitzahl": "BH12 5BB" },
  { "Partnernummer": "346748","Schultyp": "University","Land": "GB","Adresse": "University Road","Ort": "Southampton","Postleitzahl": "SO17 1BJ" },
  { "Partnernummer": "348470","Schultyp": "AHS","Land": "AT","Adresse": "Dr. Hermann Hornungg. 29","Ort": "Gleisdorf","Postleitzahl": "8200" },
  { "Partnernummer": "350191","Schultyp": "HLFS","Land": "AT","Adresse": "GrÃ¼nbergstraße 24","Ort": "Wien","Postleitzahl": "1130" },
  { "Partnernummer": "352090","Schultyp": "Universität","Land": "AT","Adresse": "Anton-von-Webern-Platz 1","Ort": "Wien","Postleitzahl": "1030" },
  { "Partnernummer": "358277","Schultyp": "Hochschule","Land": "DE","Adresse": "Lennershofstr. 140","Ort": "Bochum","Postleitzahl": "44801" },
  { "Partnernummer": "363449","Schultyp": "Uniwersytet","Land": "PL","Adresse": "Ul. Rakowicka 27","Ort": "Krakow","Postleitzahl": "31510" },
  { "Partnernummer": "364718","Schultyp": "University","Land": "GB","Adresse": "University Park","Ort": "Nottingham","Postleitzahl": "NG7 2RD" },
  { "Partnernummer": "365161","Schultyp": "University","Land": "GB","Adresse": "Whiteknights, PO Box 217","Ort": "Reading","Postleitzahl": "RG6 6AH" },
  { "Partnernummer": "366886","Schultyp": "University","Land": "GB","Adresse": "Western Bank","Ort": "Sheffield","Postleitzahl": "S10 2TN" },
  { "Partnernummer": "367206","Schultyp": "Univerzita","Land": "SK","Adresse": "Trieda A.Hlinku 2","Ort": "Nitra","Postleitzahl": "94977" },
  { "Partnernummer": "367337","Schultyp": "University","Land": "IE","Adresse": "Glasnevin, Dublin 9","Ort": "Dublin","Postleitzahl": "" },
  { "Partnernummer": "368261","Schultyp": "University","Land": "GB","Adresse": "Drake Cirkus","Ort": "Plymouth","Postleitzahl": "PL4 8AA" },
  { "Partnernummer": "368544","Schultyp": "University","Land": "GB","Adresse": "Bailrigg","Ort": "Lancaster","Postleitzahl": "LA1 4YW" },
  { "Partnernummer": "370637","Schultyp": "HLT/HLF","Land": "AT","Adresse": "Hochstraße 32c","Ort": "Semmering","Postleitzahl": "2680" },
  { "Partnernummer": "370715","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Edelseegasse 13","Ort": "Hartberg","Postleitzahl": "8230" },
  { "Partnernummer": "370834","Schultyp": "HTL","Land": "AT","Adresse": "Körösistr. 157","Ort": "Graz","Postleitzahl": "8010" },
  { "Partnernummer": "370896","Schultyp": "University","Land": "GB","Adresse": "Oxford Road","Ort": "Manchester","Postleitzahl": "M13 9PL" },
  { "Partnernummer": "370961","Schultyp": "University","Land": "GB","Adresse": "Edgbaston","Ort": "Birmingham","Postleitzahl": "B15 2TT" },
  { "Partnernummer": "372310","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Josef-Hyrtl-Platz 3","Ort": "Mödling","Postleitzahl": "2340" },
  { "Partnernummer": "373996","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Schulstraße 13","Ort": "Yspertal","Postleitzahl": "3683" },
  { "Partnernummer": "377746","Schultyp": "HLFS","Land": "AT","Adresse": "Schlossbergstraße 4","Ort": "Sitzenberg","Postleitzahl": "3454" },
  { "Partnernummer": "377840","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Stefan-Fadinger-Straße 36","Ort": "Amstetten","Postleitzahl": "3300" },
  { "Partnernummer": "378622","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Hieflauerstraße 89","Ort": "Eisenerz","Postleitzahl": "8790" },
  { "Partnernummer": "378623","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Eybnerstraße 23","Ort": "St.Pölten","Postleitzahl": "3100" },
  { "Partnernummer": "380073","Schultyp": "University","Land": "GB","Adresse": "16 University Gardens","Ort": "Glasgow","Postleitzahl": "G12 8QQ" },
  { "Partnernummer": "380898","Schultyp": "University","Land": "GB","Adresse": "The Crescent","Ort": "Salford","Postleitzahl": "M5 4WT" },
  { "Partnernummer": "381855","Schultyp": "Hochschule","Land": "AT","Adresse": "Hubertusstraße 1","Ort": "Klagenfurt","Postleitzahl": "9020" },
  { "Partnernummer": "382647","Schultyp": "Universitetas","Land": "LT","Adresse": "K. Donelaicio 73","Ort": "Kaunas","Postleitzahl": "44029" },
  { "Partnernummer": "38318","Schultyp": "AHS","Land": "AT","Adresse": "Ehrenbrunngasse 6","Ort": "Schwechat","Postleitzahl": "2320" },
  { "Partnernummer": "383952","Schultyp": "Fachhochschule","Land": "AT","Adresse": "Steinamangerstr. 21","Ort": "Pinkafeld","Postleitzahl": "7423" },
  { "Partnernummer": "386419","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Bohaterow Warszawy 10","Ort": "Wegrow","Postleitzahl": "07100" },
  { "Partnernummer": "386661","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Dr.-Karl-Widdmann-Straße 40","Ort": "Weiz","Postleitzahl": "8160" },
  { "Partnernummer": "386662","Schultyp": "Srednja sola","Land": "SI","Adresse": "Preradoviceva ul. 33","Ort": "Maribor","Postleitzahl": "2000" },
  { "Partnernummer": "386663","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Schulgasse 4","Ort": "Stockerau","Postleitzahl": "2000" },
  { "Partnernummer": "388125","Schultyp": "University","Land": "GR","Adresse": "University Campus","Ort": "Thessaloniki","Postleitzahl": "54124" },
  { "Partnernummer": "388499","Schultyp": "University","Land": "GB","Adresse": "Cambridge Campus, East Road","Ort": "Cambridge","Postleitzahl": "CB1 1PT" },
  { "Partnernummer": "388500","Schultyp": "University","Land": "GB","Adresse": "Bishop Hall Lane","Ort": "Chelmsford","Postleitzahl": "CM1 1SQ" },
  { "Partnernummer": "389251","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Friesgasse 4 / 1. Stock","Ort": "Wien","Postleitzahl": "1150" },
  { "Partnernummer": "389263","Schultyp": "University","Land": "GB","Adresse": "Hugh Owen Building / Penglais","Ort": "Aberystwyth","Postleitzahl": "SY23 3FL" },
  { "Partnernummer": "38995","Schultyp": "HTL","Land": "AT","Adresse": "Waldstrasse 3","Ort": "St.Pölten","Postleitzahl": "3100" },
  { "Partnernummer": "390548","Schultyp": "Universitat","Land": "ES","Adresse": "Camino de Vera s/n","Ort": "Valencia","Postleitzahl": "46022" },
  { "Partnernummer": "392382","Schultyp": "University","Land": "BG","Adresse": "125 Tsarigradsko Shose Blvd.,Block3","Ort": "Sofia","Postleitzahl": "1113" },
  { "Partnernummer": "396265","Schultyp": "HTL","Land": "AT","Adresse": "Wexstraße 19-23","Ort": "Wien","Postleitzahl": "1200" },
  { "Partnernummer": "399074","Schultyp": "Universitet","Land": "DK","Adresse": "Solbjerg Plads 3","Ort": "Frederiksberg","Postleitzahl": "2000" },
  { "Partnernummer": "399095","Schultyp": "Universitet","Land": "DK","Adresse": "Nordre Ringgade 1","Ort": "Aarhus","Postleitzahl": "8000" },
  { "Partnernummer": "399111","Schultyp": "Universitet","Land": "SE","Adresse": "Sveavägen 65; Box 6501","Ort": "Stockholm","Postleitzahl": "11383" },
  { "Partnernummer": "399120","Schultyp": "Universitet","Land": "SE","Adresse": "Gjuterigatan 5, P.O. Box 1026","Ort": "Jönköping","Postleitzahl": "55111" },
  { "Partnernummer": "399128","Schultyp": "Universitet","Land": "SE","Adresse": "Högskolevägen, Box 408","Ort": "Skövde","Postleitzahl": "54128" },
  { "Partnernummer": "399133","Schultyp": "Universitet","Land": "SE","Adresse": "","Ort": "Linköping","Postleitzahl": "58183" },
  { "Partnernummer": "399134","Schultyp": "Universitet","Land": "SE","Adresse": "Olofsgatan 10b; Box 256","Ort": "Uppsala","Postleitzahl": "75105" },
  { "Partnernummer": "399135","Schultyp": "Universitet","Land": "SE","Adresse": "Vasaparken, Box 100","Ort": "Göteborg","Postleitzahl": "40530" },
  { "Partnernummer": "399136","Schultyp": "Universitet","Land": "SE","Adresse": "Paradisgatan 2","Ort": "Lund","Postleitzahl": "22100" },
  { "Partnernummer": "399137","Schultyp": "Handelshoyskole","Land": "NO","Adresse": "Helleveien 30","Ort": "Bergen","Postleitzahl": "5045" },
  { "Partnernummer": "401730","Schultyp": "Universitatea","Land": "RO","Adresse": "Str. Mircea cel Batran nr.104","Ort": "Constanta","Postleitzahl": "900663" },
  { "Partnernummer": "402954","Schultyp": "HTL","Land": "AT","Adresse": "Gartenstrasse 1","Ort": "Wolfsberg","Postleitzahl": "9400" },
  { "Partnernummer": "405867","Schultyp": "HLT/HLF","Land": "AT","Adresse": "Hagauerstraße 17","Ort": "Bad Leonfelden","Postleitzahl": "4190" },
  { "Partnernummer": "410669","Schultyp": "Uniwersytet","Land": "PL","Adresse": "Al. Jednosci Narodowej 22a","Ort": "Szczecin","Postleitzahl": "70453" },
  { "Partnernummer": "410681","Schultyp": "Uniwersytet","Land": "PL","Adresse": "Plac Politechniki 1","Ort": "Warszawa","Postleitzahl": "00661" },
  { "Partnernummer": "412231","Schultyp": "Uniwersytet","Land": "PL","Adresse": "Ul. Komandorska 118/120","Ort": "Wroclaw","Postleitzahl": "53345" },
  { "Partnernummer": "412466","Schultyp": "HLT/HLF","Land": "AT","Adresse": "Kumpfallee 88-90","Ort": "Villach","Postleitzahl": "9504" },
  { "Partnernummer": "412641","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Ried 37","Ort": "Ried","Postleitzahl": "5360" },
  { "Partnernummer": "416506","Schultyp": "Gymnasium","Land": "DE","Adresse": "Verdeuer Str. 96","Ort": "Rotenburg","Postleitzahl": "27356" },
  { "Partnernummer": "417093","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "HrobÃ¡kova 11","Ort": "Bratislava","Postleitzahl": "85102" },
  { "Partnernummer": "417938","Schultyp": "HTL","Land": "AT","Adresse": "Lahnstraße 69","Ort": "Hallstatt","Postleitzahl": "4830" },
  { "Partnernummer": "418217","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Gartenstrasse 1","Ort": "Wolfsberg","Postleitzahl": "9400" },
  { "Partnernummer": "418485","Schultyp": "Wyzsza Szkola","Land": "PL","Adresse": "Ul. Zielona 27","Ort": "Nowy Sacz","Postleitzahl": "33300" },
  { "Partnernummer": "419173","Schultyp": "Universität","Land": "DE","Adresse": "Mommsenstraße 15","Ort": "Dresden","Postleitzahl": "01062" },
  { "Partnernummer": "420747","Schultyp": "Uniwersytet","Land": "PL","Adresse": "Al. Powstancow Warszawy 12","Ort": "Rzeszow","Postleitzahl": "35959" },
  { "Partnernummer": "420763","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Alter Sommer 4","Ort": "Krieglach","Postleitzahl": "8670" },
  { "Partnernummer": "430220","Schultyp": "Fachhochschule","Land": "AT","Adresse": "Währinger GÃ¼rtel 97","Ort": "Wien","Postleitzahl": "1180" },
  { "Partnernummer": "433150","Schultyp": "Univerzita","Land": "CZ","Adresse": "ZemedelskÃ¡ 1/1665","Ort": "Brno","Postleitzahl": "61300" },
  { "Partnernummer": "43676","Schultyp": "HTL","Land": "AT","Adresse": "Bad Kissingen Platz 3","Ort": "Eisenstadt","Postleitzahl": "7000" },
  { "Partnernummer": "436823","Schultyp": "Universita","Land": "IT","Adresse": "Via Zamboni 33","Ort": "Bologna","Postleitzahl": "40126" },
  { "Partnernummer": "438374","Schultyp": "AHS","Land": "AT","Adresse": "Franz-Keim-Gasse 3","Ort": "Mödling","Postleitzahl": "2340" },
  { "Partnernummer": "439310","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Radlinskeho 1725/55","Ort": "Dolny Kubin","Postleitzahl": "02601" },
  { "Partnernummer": "439312","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Inovecka 2041","Ort": "Topolcany","Postleitzahl": "95592" },
  { "Partnernummer": "439446","Schultyp": "Universita","Land": "IT","Adresse": "Piazza Marina, 61","Ort": "Palermo","Postleitzahl": "90133" },
  { "Partnernummer": "440854","Schultyp": "AHS","Land": "AT","Adresse": "Frauengasse 3-5","Ort": "Baden","Postleitzahl": "2500" },
  { "Partnernummer": "441552","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Kukicinova 2","Ort": "Trnava","Postleitzahl": "91729" },
  { "Partnernummer": "441553","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Bernolakova 2","Ort": "Martin","Postleitzahl": "03637" },
  { "Partnernummer": "441630","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Jesenskeho 259/6","Ort": "Povazska Bystrica","Postleitzahl": "01744" },
  { "Partnernummer": "441632","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Velka okruzna 32","Ort": "Zilina","Postleitzahl": "01157" },
  { "Partnernummer": "442030","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Myslenicka 1","Ort": "Pezinok","Postleitzahl": "90201" },
  { "Partnernummer": "442031","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Komenskeho 1","Ort": "Humenne","Postleitzahl": "06601" },
  { "Partnernummer": "442032","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Boleckova 2","Ort": "Nitra","Postleitzahl": "94900" },
  { "Partnernummer": "442033","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Mladeznicka 158/5","Ort": "Sered","Postleitzahl": "92601" },
  { "Partnernummer": "444986","Schultyp": "AHS","Land": "AT","Adresse": "Wohlmutstr. 3","Ort": "Wien","Postleitzahl": "1020" },
  { "Partnernummer": "445524","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Scota Viatora 4","Ort": "Ruzomberok","Postleitzahl": "03401" },
  { "Partnernummer": "445728","Schultyp": "Universitet","Land": "SE","Adresse": "Kungstensgatan 45","Ort": "Stockholm","Postleitzahl": "10239" },
  { "Partnernummer": "445833","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Kapusianska 2","Ort": "Michalovce","Postleitzahl": "07101" },
  { "Partnernummer": "449768","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Komenskeho 3425/18","Ort": "Trebisov","Postleitzahl": "07501" },
  { "Partnernummer": "449770","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Doktora Cyrila Daxnera 88","Ort": "Vranov nad Toplou","Postleitzahl": "09301" },
  { "Partnernummer": "449778","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Lucna 4","Ort": "Lucenec","Postleitzahl": "98416" },
  { "Partnernummer": "449779","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Mikszatha 1","Ort": "Rimavska Sobota","Postleitzahl": "97980" },
  { "Partnernummer": "449780","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Ul. Akademika Hronca 8","Ort": "Roznava","Postleitzahl": "04801" },
  { "Partnernummer": "455092","Schultyp": "Univerzita","Land": "CZ","Adresse": "Kamycka 129, Suchdol","Ort": "Praha","Postleitzahl": "16521" },
  { "Partnernummer": "455295","Schultyp": "Universität","Land": "AT","Adresse": "Karlsplatz 13","Ort": "Wien","Postleitzahl": "1040" },
  { "Partnernummer": "45699","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Johannes-Messner-Weg 14","Ort": "Schwaz","Postleitzahl": "6130" },
  { "Partnernummer": "45703","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Mettingerstr. 16","Ort": "Völkermarkt","Postleitzahl": "9100" },
  { "Partnernummer": "461314","Schultyp": "HTL","Land": "AT","Adresse": "Lastenstraße 1","Ort": "Klagenfurt","Postleitzahl": "9020" },
  { "Partnernummer": "461452","Schultyp": "Uniwersytet","Land": "PL","Adresse": "Ul. Akademicka 2A","Ort": "Gliwice","Postleitzahl": "44100" },
  { "Partnernummer": "462980","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Bratislavska 38","Ort": "Velky Meder","Postleitzahl": "93212" },
  { "Partnernummer": "463019","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Komarnanska 28","Ort": "Nove Zamky","Postleitzahl": "94075" },
  { "Partnernummer": "463050","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Nam. Hrdinov 7","Ort": "Surany","Postleitzahl": "94201" },
  { "Partnernummer": "463252","Schultyp": "AHS","Land": "AT","Adresse": "Bundesschulstraße 3","Ort": "Neusiedl am See","Postleitzahl": "7100" },
  { "Partnernummer": "465888","Schultyp": "Universität","Land": "AT","Adresse": "Kapitelgasse 4-6","Ort": "Salzburg","Postleitzahl": "5020" },
  { "Partnernummer": "466336","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "Nabr. Komenskeho 1","Ort": "Breclav","Postleitzahl": "69025" },
  { "Partnernummer": "466756","Schultyp": "University","Land": "FI","Adresse": "Ylioistonkatu 4 (PL33)","Ort": "Helsinki","Postleitzahl": "00014" },
  { "Partnernummer": "467863","Schultyp": "University","Land": "GB","Adresse": "Coventry","Ort": "Coventry","Postleitzahl": "CV4 7AL" },
  { "Partnernummer": "468670","Schultyp": "University","Land": "GB","Adresse": "Old Library Building","Ort": "Newcastle upon Tyne","Postleitzahl": "NE1 7RU" },
  { "Partnernummer": "471850","Schultyp": "Universita","Land": "IT","Adresse": "Via Dell'Artigliere 8","Ort": "Verona","Postleitzahl": "37129" },
  { "Partnernummer": "476129","Schultyp": "Hotelova akademia","Land": "SK","Adresse": "Stromova 34","Ort": "Piestany","Postleitzahl": "92101" },
  { "Partnernummer": "476566","Schultyp": "Universitat","Land": "ES","Adresse": "Av. de Sos Baynat s/n","Ort": "Castellon de la Plana","Postleitzahl": "12071" },
  { "Partnernummer": "47695","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Bundesschulstrasse 4","Ort": "Neusiedl am See","Postleitzahl": "7100" },
  { "Partnernummer": "477313","Schultyp": "Uniwersytet","Land": "PL","Adresse": "Al. Niepodleglosci 10","Ort": "Poznan","Postleitzahl": "61875" },
  { "Partnernummer": "477323","Schultyp": "Uniwersytet","Land": "PL","Adresse": "Ul. 1 Maja 50","Ort": "Katowice","Postleitzahl": "40287" },
  { "Partnernummer": "477327","Schultyp": "Uniwersytet","Land": "PL","Adresse": "Ul. Krakowskie Przedmiescie 26/28","Ort": "Warszawa","Postleitzahl": "00927" },
  { "Partnernummer": "477328","Schultyp": "Uniwersytet","Land": "PL","Adresse": "Ul. Jagiellonska 57/59","Ort": "Warszawa","Postleitzahl": "03301" },
  { "Partnernummer": "477393","Schultyp": "Srednja sola","Land": "SI","Adresse": "Kolodvorska ulica 2e","Ort": "Lendava-Lendva","Postleitzahl": "9220" },
  { "Partnernummer": "478049","Schultyp": "Univerzitet","Land": "RS","Adresse": "Segedinski put 9-11","Ort": "Subotica","Postleitzahl": "24000" },
  { "Partnernummer": "478938","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "Hybesova 53","Ort": "Boskovice","Postleitzahl": "68001" },
  { "Partnernummer": "479106","Schultyp": "Universitat","Land": "ES","Adresse": "Av. Blasco Ibanez 13","Ort": "Valencia","Postleitzahl": "46010" },
  { "Partnernummer": "482449","Schultyp": "Univerzita","Land": "CZ","Adresse": "Studentska 95","Ort": "Pardubice","Postleitzahl": "53210" },
  { "Partnernummer": "482898","Schultyp": "Universitatea","Land": "RO","Adresse": "Bd.Lacul Tei nr. 122-124 / Sector 2","Ort": "Bucuresti","Postleitzahl": "020396" },
  { "Partnernummer": "486562","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Polarna 1","Ort": "Kosice","Postleitzahl": "04012" },
  { "Partnernummer": "487176","Schultyp": "Univerzita","Land": "SK","Adresse": "Letna 9","Ort": "Kosice","Postleitzahl": "04200" },
  { "Partnernummer": "487191","Schultyp": "AHS","Land": "AT","Adresse": "Martin Wachter-Platz 6","Ort": "Laa an der Thaya","Postleitzahl": "2136" },
  { "Partnernummer": "490103","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Ulica Kalmana Kittenbergera 2","Ort": "Levice","Postleitzahl": "93440" },
  { "Partnernummer": "491676","Schultyp": "Fachhochschule","Land": "AT","Adresse": "Wohlmuthstraße 22","Ort": "Wien","Postleitzahl": "1020" },
  { "Partnernummer": "494944","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Murgasova 94","Ort": "Poprad","Postleitzahl": "05801" },
  { "Partnernummer": "496949","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "JarmocnÃ¡ 132","Ort": "Stara Lubovna","Postleitzahl": "06401" },
  { "Partnernummer": "499223","Schultyp": "University","Land": "FI","Adresse": "Arkadiankatu 22 (PB 479)","Ort": "Helsinki","Postleitzahl": "00101" },
  { "Partnernummer": "500246","Schultyp": "Universita","Land": "IT","Adresse": "Via Roberto Sarfatti 25","Ort": "Milano","Postleitzahl": "20100" },
  { "Partnernummer": "502917","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Kapucynska 2","Ort": "Krakow","Postleitzahl": "31113" },
  { "Partnernummer": "502922","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Os. Spoldzielcze 6","Ort": "Krakow","Postleitzahl": "31943" },
  { "Partnernummer": "503777","Schultyp": "University","Land": "FI","Adresse": "Runeberginkatu 14-16","Ort": "Helsinki","Postleitzahl": "00100" },
  { "Partnernummer": "505215","Schultyp": "AHS","Land": "AT","Adresse": "Don Boscostraße 20","Ort": "Unterwaltersdorf","Postleitzahl": "2442" },
  { "Partnernummer": "505543","Schultyp": "Universite","Land": "FR","Adresse": "23 Boulevard Albert Ier","Ort": "Nancy","Postleitzahl": "54015" },
  { "Partnernummer": "505789","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul.Romera 2","Ort": "Szczecin","Postleitzahl": "71246" },
  { "Partnernummer": "507660","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "Pionyrska 23","Ort": "Brno","Postleitzahl": "66205" },
  { "Partnernummer": "507661","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "Namesti T.G. Masaryka 3669","Ort": "Zlin","Postleitzahl": "76157" },
  { "Partnernummer": "507663","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "Masarykova 101","Ort": "Valasske Mezirici","Postleitzahl": "75701" },
  { "Partnernummer": "507668","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "Nadrazni 22","Ort": "Uherske Hradiste","Postleitzahl": "68657" },
  { "Partnernummer": "507674","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "Legionaru 1","Ort": "Hodonin","Postleitzahl": "69511" },
  { "Partnernummer": "507675","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "T.G. Masaryka 47","Ort": "Svitavy","Postleitzahl": "56802" },
  { "Partnernummer": "507677","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "PontassievskÃ¡ 3","Ort": "Znojmo","Postleitzahl": "66902" },
  { "Partnernummer": "507678","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "28. rijna 1598","Ort": "Frydek-Mistek","Postleitzahl": "73802" },
  { "Partnernummer": "507679","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "Sokola Tumy 12","Ort": "Cesky Tesin","Postleitzahl": "73701" },
  { "Partnernummer": "508587","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul.Szkolna 4","Ort": "Znin","Postleitzahl": "88400" },
  { "Partnernummer": "51217","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Leopold-Werndl-Straße 7","Ort": "Steyr","Postleitzahl": "4400" },
  { "Partnernummer": "515464","Schultyp": "Universita","Land": "IT","Adresse": "Via Balbi 5","Ort": "Genova","Postleitzahl": "16126" },
  { "Partnernummer": "515987","Schultyp": "Univerzita","Land": "SK","Adresse": "Safarikovo nam. 6","Ort": "Bratislava","Postleitzahl": "81806" },
  { "Partnernummer": "516265","Schultyp": "Universite","Land": "FR","Adresse": "Cite Scientifique","Ort": "Villeneuve d'Ascq","Postleitzahl": "59655" },
  { "Partnernummer": "516340","Schultyp": "Universitatea","Land": "RO","Adresse": "Mihai Viteazul nr.26","Ort": "Satu Mare","Postleitzahl": "440006" },
  { "Partnernummer": "51770","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Landesrat-Gebhart-Strasse 2","Ort": "Imst","Postleitzahl": "6460" },
  { "Partnernummer": "51771","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Schillerstrasse 10","Ort": "Bludenz","Postleitzahl": "6700" },
  { "Partnernummer": "51781","Schultyp": "HLA/HLW","Land": "AT","Adresse": "Zernattostrasse 2","Ort": "Spittal an der Drau","Postleitzahl": "9800" },
  { "Partnernummer": "51785","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Kaiser Max Strasse 13","Ort": "Hall in Tirol","Postleitzahl": "6060" },
  { "Partnernummer": "51790","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Karl-Schönherr-Str.2","Ort": "Innsbruck","Postleitzahl": "6020" },
  { "Partnernummer": "518469","Schultyp": "Universidade","Land": "ES","Adresse": "Rua Xeracion Nos","Ort": "Vigo","Postleitzahl": "36310" },
  { "Partnernummer": "518774","Schultyp": "Universidade","Land": "PT","Adresse": "Campus UniversitÃ¡rio de Santiago","Ort": "Aveiro","Postleitzahl": "3810" },
  { "Partnernummer": "518775","Schultyp": "Universidade","Land": "PT","Adresse": "Rua da Ilha","Ort": "Coimbra","Postleitzahl": "3000" },
  { "Partnernummer": "518865","Schultyp": "Universitet","Land": "DK","Adresse": "Skamlingvejen 32","Ort": "Kolding","Postleitzahl": "6000" },
  { "Partnernummer": "518895","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Namyslowska 94","Ort": "Dobrzen Wielki","Postleitzahl": "46081" },
  { "Partnernummer": "519407","Schultyp": "Universitatea","Land": "RO","Adresse": "Str. Unirii Nr.3","Ort": "Arad","Postleitzahl": "310123" },
  { "Partnernummer": "520004","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Gimnazjalna 3","Ort": "Raciborz","Postleitzahl": "47400" },
  { "Partnernummer": "520015","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Kosciuszki 43","Ort": "Opole","Postleitzahl": "45062" },
  { "Partnernummer": "520018","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Gen. S. Grota-Roweckiego 66","Ort": "Sosnowiec","Postleitzahl": "41200" },
  { "Partnernummer": "520615","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Stojan 1","Ort": "Spisska Nova Ves","Postleitzahl": "05201" },
  { "Partnernummer": "522658","Schultyp": "Universitet","Land": "DK","Adresse": "Campusvej 55","Ort": "Odense","Postleitzahl": "5230" },
  { "Partnernummer": "527141","Schultyp": "Szakközepiskola","Land": "HU","Adresse": "Arpad tÃ©r 1","Ort": "Köszeg","Postleitzahl": "9730" },
  { "Partnernummer": "527203","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Gdanska 17","Ort": "Tczew","Postleitzahl": "83110" },
  { "Partnernummer": "530182","Schultyp": "AHS","Land": "AT","Adresse": "Petzgasse 36","Ort": "Bad Vöslau","Postleitzahl": "2540" },
  { "Partnernummer": "532227","Schultyp": "Univerzita","Land": "SK","Adresse": "DolnozemskÃ¡ cesta 1","Ort": "Bratislava","Postleitzahl": "85235" },
  { "Partnernummer": "533670","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "Komenskeho nam, 211","Ort": "Bucovice","Postleitzahl": "68501" },
  { "Partnernummer": "533874","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "Polni 964","Ort": "Orlova","Postleitzahl": "73514" },
  { "Partnernummer": "537530","Schultyp": "Universitatea","Land": "RO","Adresse": "Calea Grivitei 2-2A / Sector 1","Ort": "Bucuresti","Postleitzahl": "010731" },
  { "Partnernummer": "537534","Schultyp": "Universitatea","Land": "RO","Adresse": "Bd-ul. Victoriei, Nr.10","Ort": "Sibiu","Postleitzahl": "550024" },
  { "Partnernummer": "537553","Schultyp": "Univerzita","Land": "CZ","Adresse": "NÃ¡m. W. Churchilla 4","Ort": "Praha","Postleitzahl": "13067" },
  { "Partnernummer": "537554","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Stefana Zeromskiego 17","Ort": "Myslenice","Postleitzahl": "32400" },
  { "Partnernummer": "538004","Schultyp": "Uniwersytet","Land": "PL","Adresse": "","Ort": "Gdansk","Postleitzahl": "80952" },
  { "Partnernummer": "538526","Schultyp": "Szakközepiskola","Land": "HU","Adresse": "Nagykar utca 1-3","Ort": "Szombathely","Postleitzahl": "9700" },
  { "Partnernummer": "538640","Schultyp": "Univerzita","Land": "SK","Adresse": "Vazovova 5","Ort": "Bratislava","Postleitzahl": "81243" },
  { "Partnernummer": "539499","Schultyp": "Liceum","Land": "PL","Adresse": "Os. Wysokie 6","Ort": "Krakow","Postleitzahl": "31826" },
  { "Partnernummer": "539838","Schultyp": "Universität","Land": "AT","Adresse": "Gregor Mendel Str. 33","Ort": "Wien","Postleitzahl": "1180" },
  { "Partnernummer": "542423","Schultyp": "Centrum Ksztalcenia Zawodowego","Land": "PL","Adresse": "Ul. Kilinskiego 31","Ort": "Sosnowiec","Postleitzahl": "41200" },
  { "Partnernummer": "543233","Schultyp": "AHS","Land": "AT","Adresse": "Roseggergasse 2-4","Ort": "Perchtoldsdorf","Postleitzahl": "2380" },
  { "Partnernummer": "545976","Schultyp": "Uniwersytet","Land": "PL","Adresse": "Ul. L. Warynskiego 4","Ort": "Opole","Postleitzahl": "45047" },
  { "Partnernummer": "54598","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Weinzierler Str. 22","Ort": "Kirchdorf an der Krems","Postleitzahl": "4560" },
  { "Partnernummer": "545980","Schultyp": "Wyzsza Szkola","Land": "PL","Adresse": "Ul. Niedzialkowskiego 18","Ort": "Opole","Postleitzahl": "45085" },
  { "Partnernummer": "546232","Schultyp": "Colegiul Economic","Land": "RO","Adresse": "Str. Oituz Nr. 31","Ort": "Sibiu","Postleitzahl": "550000" },
  { "Partnernummer": "546238","Schultyp": "Universitatea","Land": "RO","Adresse": "Calea Dumbravii Nr. 28-32","Ort": "Sibiu","Postleitzahl": "550324" },
  { "Partnernummer": "546597","Schultyp": "AHS","Land": "AT","Adresse": "Bimbo Binder Promenade 7","Ort": "St.Pölten","Postleitzahl": "3100" },
  { "Partnernummer": "548763","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "Jamocna 1","Ort": "Modry Kamen","Postleitzahl": "99280" },
  { "Partnernummer": "549304","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul Hallera 4","Ort": "Opole","Postleitzahl": "45864" },
  { "Partnernummer": "551535","Schultyp": "Centrum Ksztalcenia Zawodowego","Land": "PL","Adresse": "Ul. Powstancow SI.3","Ort": "Strzelce Opolskie","Postleitzahl": "47100" },
  { "Partnernummer": "553046","Schultyp": "Universitet","Land": "DK","Adresse": "Fredrik Bajers Vej 5,Postbox 159","Ort": "Aalborg","Postleitzahl": "9100" },
  { "Partnernummer": "553341","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "Hany Kvapilove 20","Ort": "Opava","Postleitzahl": "74601" },
  { "Partnernummer": "553946","Schultyp": "Uniwersytet","Land": "PL","Adresse": "Pl. Kopernika 11a","Ort": "Opole","Postleitzahl": "45040" },
  { "Partnernummer": "555807","Schultyp": "Stredna priemyselna skola","Land": "SK","Adresse": "Ul. Slov. partizanov 1132/52","Ort": "Povazska Bystrica","Postleitzahl": "01701" },
  { "Partnernummer": "556505","Schultyp": "Stredna odborna skola","Land": "SK","Adresse": "Mierova 727","Ort": "Strazske","Postleitzahl": "07222" },
  { "Partnernummer": "556534","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Skarbowa 2","Ort": "Kedzierzyn-Kozle","Postleitzahl": "47200" },
  { "Partnernummer": "556538","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Gory Sw. Anny 21a","Ort": "Zdzieszowice","Postleitzahl": "47330" },
  { "Partnernummer": "556539","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Pulaskiego 10","Ort": "Namyslow","Postleitzahl": "46100" },
  { "Partnernummer": "556540","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Jana Pawla II 28","Ort": "Brzeg","Postleitzahl": "49300" },
  { "Partnernummer": "557043","Schultyp": "Universidad","Land": "ES","Adresse": "Ctra. Pozuelo-Majadahonda Km. 1800","Ort": "Pozuelo de Alarcon","Postleitzahl": "28223" },
  { "Partnernummer": "557403","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Slawiecicka 79","Ort": "Kedzierzyn-Kozle","Postleitzahl": "47230" },
  { "Partnernummer": "558017","Schultyp": "Stredna priemyselna skola","Land": "SK","Adresse": "Obrancov mieru 343/1","Ort": "Dubnica nad Vahom","Postleitzahl": "01841" },
  { "Partnernummer": "558102","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Zamkowa 5","Ort": "Krapkowice","Postleitzahl": "47300" },
  { "Partnernummer": "558118","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Struga 16","Ort": "Opole","Postleitzahl": "45073" },
  { "Partnernummer": "561257","Schultyp": "University","Land": "UA","Adresse": "54/1 Prospect Peremogy","Ort": "Kyiv","Postleitzahl": "03680" },
  { "Partnernummer": "567340","Schultyp": "Universitatea","Land": "RO","Adresse": "Blvd. V. Parvan 4","Ort": "Timisoara","Postleitzahl": "300223" },
  { "Partnernummer": "568880","Schultyp": "Zespol Szkol","Land": "PL","Adresse": "Ul. Wielkie Przedmiescie 41","Ort": "Olesno","Postleitzahl": "46300" },
  { "Partnernummer": "570459","Schultyp": "Univerzita","Land": "CZ","Adresse": "17.listopadu 15/2172","Ort": "Ostrava","Postleitzahl": "70833" },
  { "Partnernummer": "571041","Schultyp": "Szakközepiskola","Land": "HU","Adresse": "Bem tÃ©r 20-22","Ort": "Györ","Postleitzahl": "9024" },
  { "Partnernummer": "575818","Schultyp": "FOS/BOS","Land": "DE","Adresse": "Wasserburgerstrasse 48","Ort": "Traunstein","Postleitzahl": "83278" },
  { "Partnernummer": "576259","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "MalinovskÃ©ho 1","Ort": "Brezno","Postleitzahl": "97754" },
  { "Partnernummer": "576410","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "TajovskÃ©ho 25","Ort": "Banska Bystrica","Postleitzahl": "97573" },
  { "Partnernummer": "576584","Schultyp": "HLA/HLW","Land": "AT","Adresse": "St. Peter 25","Ort": "St.Jakob im Rosental","Postleitzahl": "9184" },
  { "Partnernummer": "576689","Schultyp": "Obchodna akademia","Land": "SK","Adresse": "NÃ¡br. K. Petrovica 1571","Ort": "Liptovsky Mikulas","Postleitzahl": "03147" },
  { "Partnernummer": "577246","Schultyp": "Obchodni akademie","Land": "CZ","Adresse": "Leonovova 1795/3, Hranice","Ort": "Karvina","Postleitzahl": "73301" },
  { "Partnernummer": "57967","Schultyp": "HAK/HAS","Land": "AT","Adresse": "Weissenbachgasse 37","Ort": "Telfs","Postleitzahl": "6410" },
]

export const schulOrtListe = [
  "Aalborg",
"Aarhus",
"Aberdeen",
"Aberystwyth",
"Althofen",
"Amstetten",
"Arad",
"Aveiro",
"Bad Ischl",
"Bad Leonfelden",
"Bad Vöslau",
"Baden",
"Bamberg",
"Banska Bystrica",
"Bath",
"Bergen",
"Biedermannsdorf",
"Birkfeld",
"Birmingham",
"Bludenz",
"Bochum",
"Bologna",
"Boskovice",
"Bozen",
"Bratislava",
"Braunau am Inn",
"Breclav",
"Bregenz",
"Bremen",
"Brezno",
"Brixen",
"Brno",
"Bruck an der Leitha",
"Bruck an der Mur",
"Bruneck",
"Brzeg",
"Bucovice",
"Bucuresti",
"Cambridge",
"Castellon de la Plana",
"Cesky Tesin",
"Chelmsford",
"Coimbra",
"Colmar",
"Constanta",
"Coventry",
"Deutschlandsberg",
"Dijon",
"Dijon Cedex",
"Dobrzen Wielki",
"Dolny Kubin",
"Dornbirn",
"Dresden",
"Dublin",
"Dubnica nad Vahom",
"Edinburgh",
"Eferding",
"Eisenerz",
"Eisenstadt",
"Elixhausen",
"FÃ¼rstenfeld",
"Feldbach",
"Feldkirch",
"Feldkirchen in Kärnten",
"Fisciano",
"Frankfurt/Oder",
"Frauenkirchen",
"Frederiksberg",
"Freistadt",
"Frydek-Mistek",
"Gänserndorf",
"Gdansk",
"Genova",
"Getafe",
"Glasgow",
"Gleisdorf",
"Gliwice",
"GmÃ¼nd",
"Gmunden",
"Göteborg",
"Götzis",
"Graz",
"Grenoble",
"Györ",
"Hall in Tirol",
"Hallein",
"Hallstatt",
"Hartberg",
"Helsinki",
"Hodonin",
"Hollabrunn",
"Horn",
"Humenne",
"Illkirch Graffenstaden",
"Imst",
"Innichen",
"Innsbruck",
"Irdning",
"Jönköping",
"Judenburg",
"Kapfenberg",
"Karlstein",
"Karvina",
"Katowice",
"Kaunas",
"Kedzierzyn-Kozle",
"Kematen in Tirol",
"Kirchdorf an der Krems",
"Klagenfurt",
"Klosterneuburg",
"Kolding",
"Korneuburg",
"Kosice",
"Köszeg",
"Krakow",
"Krapkowice",
"Krems",
"Krieglach",
"Kuchl",
"Kufstein",
"Kyiv",
"La Rochelle",
"Laa an der Thaya",
"Lambach",
"Lancaster",
"Landeck",
"Lanzenkirchen",
"Lauterach",
"Leeds",
"Leibnitz",
"Lendava-Lendva",
"Leoben",
"Leonding",
"Levice",
"Lienz",
"Liezen",
"Linköping",
"Linz",
"Liptovsky Mikulas",
"Lucenec",
"Lund",
"Lustenau",
"MÃ¼rzzuschlag",
"Mals im Vinschgau",
"Manchester",
"Maribor",
"Martin",
"Mattersburg",
"Meran",
"Metz",
"Michalovce",
"Milano",
"Mistelbach",
"Mödling",
"Modry Kamen",
"Mulhouse Cedex",
"Murau",
"Myslenice",
"Namyslow",
"Nancy",
"Neumarkt am Wallersee",
"Neunkirchen",
"Neusiedl am See",
"Neustadt",
"Newcastle upon Tyne",
"Nitra",
"Nottingham",
"Nove Zamky",
"Nowy Sacz",
"Oberndorf bei Salzburg",
"Oberpullendorf",
"Oberwart",
"Odense",
"Olesno",
"Opava",
"Opole",
"Orlova",
"Ostrava",
"Palermo",
"Pardubice",
"Paris",
"Passau",
"Perchtoldsdorf",
"Perg",
"Pezinok",
"Piestany",
"Pinkafeld",
"Plymouth",
"Poole",
"Poprad",
"Porto",
"Povazska Bystrica",
"Poznan",
"Pozuelo de Alarcon",
"Praha",
"Raciborz",
"Raubling",
"Reading",
"Retz",
"Reutte",
"Ried",
"Ried im Innkreis",
"Rimavska Sobota",
"Rohrbach in Oberösterreich",
"Rosenheim",
"Rotenburg",
"Roznava",
"Ruzomberok",
"Rzeszow",
"S.Ulrich in Gröden",
"Saalfelden",
"Salford",
"Salzburg",
"Sand in Taufers",
"Satu Mare",
"Schärding",
"Schlanders",
"Schwaz",
"Schwechat",
"Semmering",
"Sered",
"Sheffield",
"Sibiu",
"Siezenheim",
"Sitzenberg",
"Skövde",
"Sofia",
"Sosnowiec",
"Southampton",
"Spisska Nova Ves",
"Spittal an der Drau",
"St Andrews",
"St.Florian",
"St.Jakob im Rosental",
"St.Johann im Pongau",
"St.Johann in Tirol",
"St.Pölten",
"St.Veit an der Glan",
"Stams",
"Stara Lubovna",
"Stegersbach",
"Sterzing",
"Steyr",
"Stirling",
"Stockerau",
"Stockholm",
"Strasbourg",
"Strazske",
"Strzelce Opolskie",
"Subotica",
"Surany",
"Svitavy",
"Szczecin",
"Szombathely",
"Tamsweg",
"Tczew",
"Telfs",
"Thessaloniki",
"Timisoara",
"Topolcany",
"Traun",
"Traunstein",
"Trebisov",
"Treibach-Althofen",
"Trento",
"Trnava",
"Tulln",
"Uherske Hradiste",
"Unterwaltersdorf",
"Uppsala",
"Valasske Mezirici",
"Valencia",
"Valladolid",
"Velky Meder",
"Verona",
"Vigo",
"Viktring",
"Villach",
"Villeneuve d'Ascq",
"Villingen-Schwenningen",
"Vöcklabruck",
"Völkermarkt",
"Vranov nad Toplou",
"Waidhofen an der Thaya",
"Waidhofen an der Ybbs",
"Warszawa",
"Wegrow",
"Weiden",
"Weiz",
"Wels",
"Wien",
"Wiener Neustadt",
"Wölfnitz",
"Wolfsberg",
"Wörgl",
"Wroclaw",
"Ybbs an der Donau",
"Yspertal",
"Zdzieszowice",
"Zell am See",
"Zell am Ziller",
"Zilina",
"Zlin",
"Znin",
"Znojmo",
"Zwettl"
]